set CMAKE_GENERATOR_PLATFORM=
set CMAKE_GENERATOR_TOOLSET=
set CMAKE_GENERATOR=Ninja
set CMAKE_ARGS=-DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX -DUSEARROW=ON -DPython_ROOT_DIR=$PREFIX -DPython_FIND_VIRTUALENV=ONLY
python -m pip install . -vv