{% set name = "nyxus" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/nyxus/archive/refs/heads/main.zip
  sha256: 412b4c8df2a457f7847f42a1f08bebca06f66721929ff82d0eec36d2133868de
  patches:
    - 0000-win_2022.patch
build:
  number: 7
  skip: true  # [py<36]
  missing_dso_whitelist:
    - '*/nvcuda.dll'   # [win]
  ignore_run_exports_from:
  # The CXX standard library is unused on linux, but used on osx
    - {{ compiler('cxx') }}  # [linux]

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - git
    - ninja  # [win]  

  host:
    - python
    - setuptools
    - pip
    - z5py  # [cuda_compiler_version != "10.2" or not linux] 
    - libtiff
    - libboost-headers
    - nlohmann_json
    - blosc  # [cuda_compiler_version != "10.2" or not linux]
    - pybind11
    - xtensor  # [cuda_compiler_version != "10.2" or not linux] 
    - xsimd  # [cuda_compiler_version != "10.2" or not linux] 
    - numpy
    - pandas
    - dcmtk
    - fmjpeg2koj
    - libarrow
    - m2-patch  # [win]
    - libcufft-dev  # [(cuda_compiler_version or "").startswith("12")]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('cudatoolkit') }}  # [cuda_compiler_version != "None"]
    - pandas

test:
  requires:
    - pip

  imports:
    - nyxus
  commands:
    - pip check

about:
  home: https://github.com/PolusAI/nyxus
  summary: Scalable library for calculating features from intensity-label image data
  description: |
    Nyxus is a feature-rich, highly optimized, Python/C++ application capable of analyzing images 
    of arbitrary size and assembling complex regions of interest (ROIs) split across multiple image 
    tiles and files. Nyxus can be used via Python or command line and is available in containerized 
    form for reproducible execution. Nyxus computes over 450 combined intensity, texture, and 
    morphological features at the ROI or whole image level with more in development. 
    Key features that make Nyxus unique among other image feature extraction applications is its 
    ability to operate at any scale, its highly validated algorithms, 
    and its modular nature that makes the addition of new features straightforward.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nyxus.readthedocs.io/en/latest/
  dev_url: https://github.com/PolusAI/nyxus

extra:
  recipe-maintainers:
    - sameeul
